const PRODUCTS = [
	{
		id: 1,
	    title: 'Light blue shirt',
		price: '$122.99',
		image: '../images/1.jpg',
		details:'Get some inspiration from our clothes description example. Keep in mind that you want your clothing descriptions to sound natural and confident.', 
		category:"men",
	},
	{
		id: 2,
	    title: 'White & red shirt',
		price: '$14.89',
		image: '../images/2.jpg',
		details:'Get some inspiration from our clothes description example. Keep in mind that you want your clothing descriptions to sound natural and confident.',
		category:"men",
	},
	{
		id: 3,
	    title: 'Dark blue shirt',
		price: '$13.67',
		image: '../images/3.jpg',
		details:'Get some inspiration from our clothes description example. Keep in mind that you want your clothing descriptions to sound natural and confident.',
		category:"men",
	},
	{
		id: 4,
	    title: 'sky blue shirt',
		price: '$27.56',
		image: '../images/4.jpg',
		details:'Get some inspiration from our clothes description example. Keep in mind that you want your clothing descriptions to sound natural and confident.',
		category:"men",
	},
	{
		id: 5,
	    title: 'Brown and Dark blue shirt',
		price: '$33.06',
		image: '../images/5.jpg',
		details:'Get some inspiration from our clothes description example. Keep in mind that you want your clothing descriptions to sound natural and confident.',
		category:"men",
	},
	{
		id: 6,
	    title: 'Gray tiger T-shirt',
		price: '$33.20',
		image: '../images/6.jpg',
		details:'These t-shirts are a comfortable and durable alternative to standard cotton tees. It’s designed to be worn all day by the man in demand. This classic design will keep you looking presentable on the go with a gentle fabric for comfort all day.You won’t perform at your best if you’re irritated by your clothing. This sleek take on a well-loved classic features a tried and tested spread collar and slim fit.',
		category:"men",
	},
	{
		id: 7,
	    title: 'Gary t-shirt',
		price: '$25.43',
		image: '../images/7.jpg',
		details:'These t-shirts are a comfortable and durable alternative to standard cotton tees. It’s designed to be worn all day by the man in demand. This classic design will keep you looking presentable on the go with a gentle fabric for comfort all day.You won’t perform at your best if you’re irritated by your clothing. This sleek take on a well-loved classic features a tried and tested spread collar and slim fit.',
		category:"men",
	},
	{
		id: 8,
	    title: 'Wave t-shirt',
		price: '$50.98',
		image: '../images/8.jpg',
		details:'These t-shirts are a comfortable and durable alternative to standard cotton tees. It’s designed to be worn all day by the man in demand. This classic design will keep you looking presentable on the go with a gentle fabric for comfort all day.You won’t perform at your best if you’re irritated by your clothing. This sleek take on a well-loved classic features a tried and tested spread collar and slim fit.',
		category:"men",
	},
	{
		id: 9,
	    title: 'Dark blue t-shirt',
		price: '$87.22',
		image: '../images/9.jpg',
		details:'Get some inspiration from our clothes description example. Keep in mind that you want your clothing descriptions to sound natural and confident.',
		category:"men",
	},
	{
		id: 10,
	    title: 'Black t-shirt',
		price: '$47.99',
		image: '../images/10.jpg',
		details:'Get some inspiration from our clothes description example. Keep in mind that you want your clothing descriptions to sound natural and confident.',
		category:"men",
	},
	{
		id: 11,
	    title: 'Black designed t-shirt',
		price: '$69.99',
		image: '../images/11.jpg',
		details:'Get some inspiration from our clothes description example. Keep in mind that you want your clothing descriptions to sound natural and confident.',
		category:"women",
	},
	{
		id: 12,
	    title: 'white flowered t-shirt',
		price: '$33.99',
		image: '../images/12.jpg',
		details:'Get some inspiration from our clothes description example. Keep in mind that you want your clothing descriptions to sound natural and confident.',
		category:"women",
	},
	{
		id: 13,
	    title: 'Dark blue t-shirt',
		price: '$57.99',
		image: '../images/13.jpg',
		details:'Get some inspiration from our clothes description example. Keep in mind that you want your clothing descriptions to sound natural and confident.',
		category:"women",
	},
	{
		id: 14,
	    title: 'Light Green t-shirt',
		price: '$49.99',
		image: '../images/14.jpg',
		details:'Get some inspiration from our clothes description example. Keep in mind that you want your clothing descriptions to sound natural and confident.',
		category:"women",
	},
	{
		id: 15,
	    title: 'White paris t-shirt',
		price: '$25.99',
		image: '../images/15.jpg',
		details:'Get some inspiration from our clothes description example. Keep in mind that you want your clothing descriptions to sound natural and confident.',
		category:"women",
	},
	{
		id: 16,
	    title:'Brown doted',
		price: '$22.99',
		image: '../images/16.jpg',
		details:'Get some inspiration from our clothes description example. Keep in mind that you want your clothing descriptions to sound natural and confident.',
		category:"women",
	},
	{
		id: 17,
	    title: 'full Black',
		price: '$54.99',
		image: '../images/17.jpg',
		details:'Get some inspiration from our clothes description example. Keep in mind that you want your clothing descriptions to sound natural and confident.',
		category:"women",
	},
	{
		id: 18,
	    title: 'white with flower doted',
		price: '$39.99',
		image: '../images/18.jpg',
		details:'Get some inspiration from our clothes description example. Keep in mind that you want your clothing descriptions to sound natural and confident.',
		category:"women",
	},
	{
		id: 19,
	    title: 'Red doted',
		price: '$29.99',
		image: '../images/19.jpg',
		details:'Get some inspiration from our clothes description example. Keep in mind that you want your clothing descriptions to sound natural and confident.',
		category:"women",
	},
	{
		id: 20,
	    title: 'red top and red doted',
		price: '$49.99',
		image: '../images/20.jpg',
		details:'Get some inspiration from our clothes description example. Keep in mind that you want your clothing descriptions to sound natural and confident.',
		category:"women",
	},
	{
		id: 21,
	    title: 'spidy t-shirt',
		price: '$19.99',
		image: '../images/21.jpg',
		details:'Get some inspiration from our clothes description example. Keep in mind that you want your clothing descriptions to sound natural and confident.',
		category:"kid",
	},
	{
		id: 22,
	    title: 'Avengers t-shirt',
		price: '$21.99',
		image: '../images/22.jpg',
		details:'Get some inspiration from our clothes description example. Keep in mind that you want your clothing descriptions to sound natural and confident.',
		category:"kid",
	},
	{
		id: 23,
	    title: 'Micky t-shirt',
		price: '$18.99',
		image: '../images/23.jpg',
		details:'Get some inspiration from our clothes description example. Keep in mind that you want your clothing descriptions to sound natural and confident.',
		category:"kid",
	},
	{
		id: 24,
	    title: 'green t-shirt',
		price: '$24.99',
		image: '../images/24.jpg',
		details:'Get some inspiration from our clothes description example. Keep in mind that you want your clothing descriptions to sound natural and confident.',
		category:"kid",
	},
	{
		id: 25,
	    title: 'Football t-shirt',
		price: '$17.99',
		image: '../images/25.jpg',
		details:'Get some inspiration from our clothes description example. Keep in mind that you want your clothing descriptions to sound natural and confident.',
		category:"kid",
	},
];

export default PRODUCTS;
